# Generated by Django 3.1.1 on 2020-09-19 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoServer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachedphoto',
            name='to_delete',
        ),
        migrations.AlterField(
            model_name='cachedphoto',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
